package com.year20.day2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Input {
    private String input =
            "2-5 z: zzztvz\n" +
                    "2-8 d: pddzddkdvqgxndd\n" +
                    "4-14 r: rrrjrrrrrrbrrccrr\n" +
                    "2-7 r: zrgsnrr\n" +
                    "9-10 z: zzzxwzznpd\n" +
                    "8-13 g: gggggggxgggghggg\n" +
                    "1-6 c: xcccxcccccz\n" +
                    "3-4 b: bxbt\n" +
                    "8-11 d: dddddddzddv\n" +
                    "4-14 m: kxdmmmdmfwmmmdfr\n" +
                    "16-17 g: ggggggggggggggggg\n" +
                    "2-3 f: ddvdlff\n" +
                    "9-11 g: ggggpfgggggg\n" +
                    "7-8 c: fdhctccc\n" +
                    "3-6 c: tmcdcncqcvccg\n" +
                    "2-3 l: clllll\n" +
                    "1-9 b: bbbbbbbbbb\n" +
                    "10-15 w: wglmwwwrnnzgwhhwvvd\n" +
                    "10-14 g: ggggggxsgggqggg\n" +
                    "9-19 q: fjlqbvtdngwvtbnsgfm\n" +
                    "1-2 k: kgbkkv\n" +
                    "4-10 m: mmmmtmmmmgm\n" +
                    "3-4 h: hplh\n" +
                    "5-7 q: qqqqrqk\n" +
                    "3-12 v: zbvlbpxcrnvvwjpwl\n" +
                    "1-4 r: crrr\n" +
                    "4-5 h: hhhrj\n" +
                    "2-4 r: mhrr\n" +
                    "9-10 c: pccccsccbk\n" +
                    "10-16 n: drnhqnnnnqnnpxmh\n" +
                    "5-6 v: vvvnvvg\n" +
                    "11-12 c: ccccgcccccpc\n" +
                    "5-10 b: bdbjbbfmfbb\n" +
                    "9-13 w: zwbwwzhwwkwsxdfwglx\n" +
                    "5-19 v: vvvvvqrvvfvgvvvvmvv\n" +
                    "3-9 d: dddgztdljb\n" +
                    "12-13 s: swssssrsssshx\n" +
                    "5-6 l: dllkljq\n" +
                    "4-5 q: qqqsdqq\n" +
                    "2-4 w: tmwg\n" +
                    "10-12 l: llllsldflllllljjlxl\n" +
                    "3-11 s: sjtsssssksbs\n" +
                    "1-5 v: hvvtmvgvv\n" +
                    "3-12 g: ggvgkgfgggghgg\n" +
                    "3-4 p: ccpp\n" +
                    "3-9 v: vfvvvvvvvvvvvr\n" +
                    "8-16 k: kkkkkkkkkkkkkwkkkk\n" +
                    "8-9 x: wxbrxfdrw\n" +
                    "7-9 n: nnnfnnnnn\n" +
                    "7-11 w: wwwwxwwwwwzxw\n" +
                    "6-9 n: nknnhnnnnlnnn\n" +
                    "10-12 l: qllllllllqbl\n" +
                    "17-19 p: pppppppppppppwppkpp\n" +
                    "4-5 q: qqqqqq\n" +
                    "7-15 v: vvvbmbjvjznzdhfvtn\n" +
                    "3-12 w: wwwwwdwwwwwwtwwwww\n" +
                    "7-10 x: mmgmknpvdbxdl\n" +
                    "9-10 v: jljttxpvvv\n" +
                    "11-15 d: dshddnddqdhddvm\n" +
                    "1-3 r: vrqrrr\n" +
                    "6-7 c: ltcbpccw\n" +
                    "5-13 q: qqqqcqqqxqrqg\n" +
                    "3-7 l: lhlmhzl\n" +
                    "2-3 l: lxntjnttkllll\n" +
                    "3-4 b: bbnsb\n" +
                    "5-6 j: rjppzvjdjj\n" +
                    "4-10 g: fgggjgvfggggggsggm\n" +
                    "11-12 z: ztzzzkzzzzsvzzzzt\n" +
                    "2-3 h: hcvbf\n" +
                    "7-13 s: sswkwhsdqsdcs\n" +
                    "3-10 j: mghjglnbdhjp\n" +
                    "6-8 x: dfxrxxsxpsxxxxmc\n" +
                    "11-12 f: fffmfcdpffmpflfffdw\n" +
                    "4-7 n: nnnknncnn\n" +
                    "2-6 k: tzqlzqhrncvktfwvswt\n" +
                    "2-4 h: pqplh\n" +
                    "8-13 h: zhlwqvmnkjhhtkf\n" +
                    "2-3 l: llll\n" +
                    "19-20 j: jjjjjjjjjjjjjjjjjrjj\n" +
                    "3-14 n: crnnrgpmxxlrfljk\n" +
                    "2-4 t: stpr\n" +
                    "11-13 c: cctcccccccccccc\n" +
                    "5-6 q: fqqqqqdwtwqjq\n" +
                    "6-7 z: zzzzzzg\n" +
                    "8-16 j: njjgsjjljktjcbjvjc\n" +
                    "3-6 c: swjccc\n" +
                    "5-7 h: ghvwjmzm\n" +
                    "9-12 s: sssssmvtdckmfs\n" +
                    "3-4 r: bsrm\n" +
                    "6-7 c: ccctcccc\n" +
                    "6-10 t: swndrtcvtl\n" +
                    "13-19 v: vjvxvvvdvvvvvvdvblv\n" +
                    "5-7 w: hnwwwtwp\n" +
                    "8-9 k: kkkkkktzxkkv\n" +
                    "4-6 g: xpsxgs\n" +
                    "2-3 r: xrrdxm\n" +
                    "2-9 f: ffvqxxvsf\n" +
                    "7-10 t: tttttttttt\n" +
                    "4-6 q: bbqqqqqqbq\n" +
                    "7-9 q: xjcwqhprgh\n" +
                    "3-6 j: jjjjjjjxjjj\n" +
                    "1-3 l: blll\n" +
                    "2-5 p: phbppp\n" +
                    "3-4 p: phpb\n" +
                    "2-15 r: mwgnrkxrrbmgpzrdrr\n" +
                    "8-13 x: jsrlvxmxwglkh\n" +
                    "4-11 b: ctcbsjgjplbthhrskfnb\n" +
                    "6-7 q: qqqqqfvcq\n" +
                    "10-11 d: ddddddjdbndddd\n" +
                    "8-9 p: pppppppkf\n" +
                    "10-14 q: qqqqqqnqzgqsqv\n" +
                    "12-13 b: bbbbbbbbbbbbb\n" +
                    "6-11 h: khnkthfhhdhrhh\n" +
                    "5-6 g: gzggwcgq\n" +
                    "2-4 f: fbfg\n" +
                    "6-9 f: ffvfsfvffxff\n" +
                    "6-7 t: tsfdltt\n" +
                    "14-17 t: tttttttttttxtcttp\n" +
                    "3-4 v: vwtv\n" +
                    "7-10 x: pxmldqqxmw\n" +
                    "1-2 s: pdssssssss\n" +
                    "5-6 n: snwnml\n" +
                    "3-8 t: tjnpjqzxbj\n" +
                    "5-7 n: mxkqfnjb\n" +
                    "4-12 q: qqqkqqqqqqqkqqq\n" +
                    "4-5 d: pjhnsfdgddjsddvpxxd\n" +
                    "14-15 t: trttdtxwtdmtttt\n" +
                    "3-4 j: jjvz\n" +
                    "1-2 p: xqpppp\n" +
                    "11-15 d: dddpdddddddddddq\n" +
                    "15-16 b: bnbbbbbbbbbtbbdbb\n" +
                    "9-11 w: wwwnwwmwbghw\n" +
                    "15-18 g: tjwqbgwmvpvghxgzkgj\n" +
                    "3-4 j: jjps\n" +
                    "9-12 f: ffflfffmfnffvff\n" +
                    "1-3 g: gbgstndgggqrdbtpdqdr\n" +
                    "4-6 f: fflxfqffff\n" +
                    "10-14 t: ttttttttttttttttt\n" +
                    "1-7 v: vvsqlvvvvkj\n" +
                    "3-7 b: wvbxlwbjtbbbvh\n" +
                    "3-7 p: hqvsvpn\n" +
                    "2-6 f: fkwfhf\n" +
                    "3-11 d: dzrwnffrdvs\n" +
                    "8-9 s: sssdssztlssqksx\n" +
                    "12-15 t: tttttttttthtttt\n" +
                    "5-6 m: mmmmmmmm\n" +
                    "2-3 n: dnnl\n" +
                    "12-16 w: wrwwtvwwwwwwwwww\n" +
                    "2-4 j: jjjjsj\n" +
                    "7-11 x: xxxxxtcxxxlxxx\n" +
                    "8-17 n: nbngnnnsnjnbhnntzwxt\n" +
                    "5-6 b: tmbdgn\n" +
                    "15-16 x: xqlpjxbbxnrbxxxxqmkf\n" +
                    "1-3 c: ccclf\n" +
                    "12-14 m: zhmmmzltwhrmfmx\n" +
                    "15-17 c: ccvcxcmccgccccbcccc\n" +
                    "10-13 k: mkgkljkkkjkkg\n" +
                    "1-4 b: ckdr\n" +
                    "10-12 b: bvfbgbbbbbbb\n" +
                    "2-4 v: jfvcv\n" +
                    "2-7 p: jswmqpmc\n" +
                    "11-16 b: bbbncbpmbjbbvgrb\n" +
                    "1-6 n: ktjcwr\n" +
                    "2-9 l: lllrwljlnlwllln\n" +
                    "17-18 h: hhhhhhhhhhhhhhhhzfh\n" +
                    "9-14 b: bbbsbqbbjjbbkb\n" +
                    "7-12 j: jjjjjwwjjjjcj\n" +
                    "10-13 w: wfwwwwwwwjwww\n" +
                    "2-6 j: bjghpj\n" +
                    "13-16 z: zzzzzzzzbzzzzzvg\n" +
                    "10-11 f: ffffkfffcfxff\n" +
                    "3-4 m: mmmmkjvzmkp\n" +
                    "2-5 k: kkkkk\n" +
                    "5-6 r: rrbrrs\n" +
                    "1-2 c: ccqjmc\n" +
                    "13-14 r: rrrrrrrrrrrrztr\n" +
                    "8-12 z: zrzzzzzqbzvdz\n" +
                    "4-9 m: hlgmtvvqs\n" +
                    "9-10 t: tthttrtbrnt\n" +
                    "2-4 k: snpkzhck\n" +
                    "12-13 x: wlxwwxxxhgxxx\n" +
                    "11-16 h: ncmfhhvgghhhhhjhd\n" +
                    "13-15 g: sgxgfntgjnxkgbgm\n" +
                    "4-13 s: vqkslldmgmfrd\n" +
                    "3-14 z: zzzzzzzzzzzzzzzz\n" +
                    "14-15 c: ccccvccccccsmlpcfccx\n" +
                    "4-5 p: pppppp\n" +
                    "9-10 z: kgblzrqbzz\n" +
                    "13-15 p: pppppptpmppbpppqpp\n" +
                    "7-8 b: dntbbcmswb\n" +
                    "16-17 d: dddddddddddddddgd\n" +
                    "10-11 r: rrrsrmrrrqtr\n" +
                    "2-3 q: qtqgz\n" +
                    "6-8 c: xztzfkcch\n" +
                    "14-15 l: lllflllllllllzsl\n" +
                    "1-6 s: zssssss\n" +
                    "5-8 d: hdddwddvdpd\n" +
                    "10-12 j: jjjjjjjjjpjbj\n" +
                    "1-9 q: tqqqqqqqqnqqwqk\n" +
                    "2-4 t: shpwwttwqb\n" +
                    "8-9 s: xrssssssz\n" +
                    "3-4 c: cjcfc\n" +
                    "3-10 v: rfvzsncmfv\n" +
                    "4-7 t: lshczltjfqkmkt\n" +
                    "13-16 x: xxxxxxxfxxxxzxxrxx\n" +
                    "1-3 z: pzkzlzmzz\n" +
                    "4-5 d: ddkbfdtdd\n" +
                    "9-10 r: rrrrrrrrlfkj\n" +
                    "3-7 s: svtbsssjsldts\n" +
                    "10-13 c: ccccgxzqtctrc\n" +
                    "1-7 q: zgwqgrx\n" +
                    "6-8 f: ffnffrfg\n" +
                    "4-5 f: kffcffp\n" +
                    "1-2 m: ggcm\n" +
                    "5-6 z: zzzdgz\n" +
                    "9-14 j: jjjnjjjjjjjjjjjj\n" +
                    "2-17 d: xttgzggnfhsrjqdbppps\n" +
                    "5-6 f: xrcfff\n" +
                    "1-3 z: wzzg\n" +
                    "1-2 h: hhhvl\n" +
                    "13-17 q: qqqqqqqqqqmqqqqqqq\n" +
                    "2-3 q: bjqq\n" +
                    "1-5 w: zwwwgww\n" +
                    "5-7 s: jnvpmgj\n" +
                    "9-10 q: zctgztwpqq\n" +
                    "16-20 j: jkjjkjnjwqqjjjzgjjpk\n" +
                    "16-20 k: kkkkkkkkkkkkkkkkkkkk\n" +
                    "17-18 d: dddddddddddddddddbd\n" +
                    "3-5 d: dngrhxb\n" +
                    "10-12 t: tmttttttttrttwh\n" +
                    "7-9 q: nqqqkqcqqqqq\n" +
                    "7-9 z: zqzzzzwctng\n" +
                    "10-13 d: dddjldsddkddjpddd\n" +
                    "3-7 g: lgglgggggphx\n" +
                    "6-7 b: llkbcdxwtzrblp\n" +
                    "1-5 s: dssdscpzwcn\n" +
                    "2-6 h: hhphhhhhh\n" +
                    "4-13 z: smkzzpzjfzzbzqzxzjz\n" +
                    "2-5 j: jjjjjj\n" +
                    "8-11 p: lgmppspppppk\n" +
                    "9-10 c: ccccccccdnkc\n" +
                    "3-9 m: mmfmmmmpkmsmmm\n" +
                    "13-15 m: mmmmkmmmmmmmgmhmmm\n" +
                    "5-6 x: xxxxxxx\n" +
                    "10-14 b: bbbjbqbbwcbbbb\n" +
                    "3-12 f: ffmfffffffnzfffff\n" +
                    "11-12 m: mmmnmmmmmmmmm\n" +
                    "8-12 v: jptmbccvmvsxchfvv\n" +
                    "4-5 s: ssssns\n" +
                    "12-14 j: jjjjjjdjjjjvjhjjj\n" +
                    "11-13 j: wjjjljjjcjjjjqjjp\n" +
                    "1-7 g: ggggggggdg\n" +
                    "2-3 v: bkjqv\n" +
                    "4-13 q: qzhldwthbwgtr\n" +
                    "12-13 p: ppplppdgpppppp\n" +
                    "11-12 f: flffxfpffprgfff\n" +
                    "8-14 b: mbbbbbtbwbhstbbbbbbb\n" +
                    "6-7 m: bqmsmmm\n" +
                    "1-3 w: qxlggmxtwj\n" +
                    "3-17 c: dwbkjcwqcrccbcxcnvxc\n" +
                    "11-13 p: ppxppppdppxpzpppp\n" +
                    "4-10 v: vfvvfvzvqv\n" +
                    "1-7 m: mmmxmmmmmbmmrmmmmmm\n" +
                    "2-12 x: xrdxwxzwfxpxtqxxxgxp\n" +
                    "6-11 w: swzwwkddmsrxwzfg\n" +
                    "6-8 g: ggggggggggg\n" +
                    "3-4 h: tzshs\n" +
                    "7-8 t: zjtzpclm\n" +
                    "5-6 k: brzkzk\n" +
                    "14-15 c: cccccccccjccccc\n" +
                    "2-3 h: hhfh\n" +
                    "15-19 w: wwwwwwwkzxwwwwwwwwh\n" +
                    "8-10 f: mjmwqnlnhf\n" +
                    "3-8 l: ksllllplllc\n" +
                    "1-3 q: gjmhq\n" +
                    "2-9 l: lwklcxllf\n" +
                    "5-7 p: ppcclscppgdxmg\n" +
                    "3-6 z: fpxmpz\n" +
                    "8-11 r: vrrrrrrrrrrrrrs\n" +
                    "1-7 q: cqqqqqgq\n" +
                    "13-14 t: tttztttttttttt\n" +
                    "4-6 q: qzkqsqzmhhq\n" +
                    "8-14 l: llllfllplllgzll\n" +
                    "5-9 m: mmmtmmmmm\n" +
                    "9-14 l: llllllllrllllltl\n" +
                    "3-4 r: czrr\n" +
                    "2-5 s: lssslssnmfqss\n" +
                    "14-17 h: hhhhhhhhhhhhhhhhhh\n" +
                    "3-4 x: xxxx\n" +
                    "7-8 x: zdjbxxsl\n" +
                    "10-13 n: ffrnphpzhnfxnncptmn\n" +
                    "7-11 m: mmmmmmdmmmmmf\n" +
                    "1-2 j: jjjjjjjjjtj\n" +
                    "2-6 g: kglgsq\n" +
                    "3-8 x: csvxxxxxztxdxpw\n" +
                    "3-9 m: qbqwfmfpjmbnbcccgfgk\n" +
                    "2-14 v: rmqhqlrvcjdhpw\n" +
                    "8-9 p: pppppppvwpm\n" +
                    "8-12 f: zvfjxbdgzjbplm\n" +
                    "2-3 f: frff\n" +
                    "7-9 f: htkxffclfr\n" +
                    "4-7 v: cvqjctzvzvvv\n" +
                    "6-7 f: fjffflj\n" +
                    "1-4 b: tbnpb\n" +
                    "8-10 t: tjpbtfzhtfsdjtlttttt\n" +
                    "8-12 h: hhhhhhhhhhhrh\n" +
                    "3-5 n: hxbwgjchklnplnb\n" +
                    "1-2 z: jzvz\n" +
                    "4-7 z: vzzzvcz\n" +
                    "11-12 f: fffffvcfskcfcfftqf\n" +
                    "2-5 p: cxktpckkqkgjpptvgp\n" +
                    "9-16 b: bbbbbbbbkbbbbbbbbbbb\n" +
                    "10-11 p: jcpnpppxpppb\n" +
                    "7-9 n: sncnrzncnzdnngn\n" +
                    "10-11 n: ttqrrkbspnn\n" +
                    "11-19 c: ccczncccccsccpccccjc\n" +
                    "1-2 h: hhhbwhhknzf\n" +
                    "5-8 q: zxbtktkf\n" +
                    "2-6 x: trxhzl\n" +
                    "1-5 d: dskddkqdgqkhcz\n" +
                    "7-12 c: ccccccccccccc\n" +
                    "7-9 t: kskrrhtxtvsqzt\n" +
                    "5-12 v: vvvjvwrdfscv\n" +
                    "6-10 z: pzznznzczkwzzzmzz\n" +
                    "15-18 t: tttttntttttttttttttt\n" +
                    "4-6 m: bxmmmm\n" +
                    "2-8 k: tkkhqwkkkpk\n" +
                    "6-11 p: pppppgmpppppp\n" +
                    "7-10 b: bkbcbbrrbr\n" +
                    "6-11 c: cctccccbnbcvccc\n" +
                    "2-5 t: ccpxgwzqktxwjf\n" +
                    "4-11 s: sssssscsssssg\n" +
                    "3-4 d: ndpk\n" +
                    "3-4 z: gjzzzkbhzzs\n" +
                    "8-9 t: ttttttttt\n" +
                    "5-10 l: lllldmmlln\n" +
                    "9-15 j: njzjgjjjjjjjprjjj\n" +
                    "5-7 p: zppppppgkp\n" +
                    "2-6 r: rvdrrrgdnrrrlrr\n" +
                    "6-7 k: kkkkkkkk\n" +
                    "3-4 x: nxxxmtmljgldjx\n" +
                    "2-6 f: qfxxxftf\n" +
                    "1-9 z: zzdlqgzwzzjw\n" +
                    "6-8 n: rnjnstwm\n" +
                    "4-6 w: vhfhwckw\n" +
                    "3-7 k: kkpkkfpk\n" +
                    "5-7 k: kkkfzkhkk\n" +
                    "1-11 j: jjjtjjjjmjs\n" +
                    "2-17 w: wlwdkkwmkwskpstxvrwr\n" +
                    "5-11 g: kgpgjspqlwnx\n" +
                    "2-6 l: lpllld\n" +
                    "1-6 d: xwkvgvkdxlljpdqwmhs\n" +
                    "5-6 z: llrzzsz\n" +
                    "4-5 l: lllll\n" +
                    "18-19 g: gggggggngggggggggggg\n" +
                    "1-10 x: kkdxwkrtfh\n" +
                    "3-4 t: ttrqzttbsrt\n" +
                    "14-16 s: ssshsssssssssnsss\n" +
                    "2-6 k: kjzkxkkhkp\n" +
                    "2-10 b: bbbbbbbbbbbbbb\n" +
                    "1-9 v: vvvvvvvvvvv\n" +
                    "11-12 m: mqmmmmmmmmhsl\n" +
                    "5-6 s: sssmsss\n" +
                    "14-20 s: srssssssdsssskssksvs\n" +
                    "1-3 r: rrrr\n" +
                    "4-7 d: zddkdptdfdw\n" +
                    "6-7 g: rggglggtgkgg\n" +
                    "3-5 c: bcctcvpcprcccqccpcrc\n" +
                    "8-9 r: rrrxzrrlmrd\n" +
                    "12-17 c: hcctccccbqcctscsscv\n" +
                    "15-16 d: dkddddjdddddsdhwdddj\n" +
                    "13-14 b: blbbbbqbhbbbmz\n" +
                    "2-10 p: hvxqpjqstv\n" +
                    "1-4 p: plxp\n" +
                    "3-6 z: zzdlzqjzzz\n" +
                    "1-14 s: qsssssssslshswsjh\n" +
                    "3-5 r: grrrnrrrsvrrrdrrrjrr\n" +
                    "1-4 d: dfdjdxbpdddf\n" +
                    "2-3 p: pppppp\n" +
                    "16-18 c: cmcccjxfclcgmchswq\n" +
                    "9-11 x: xxrxxxxxvxrxx\n" +
                    "13-14 p: dpppppsppspftpppwp\n" +
                    "15-19 h: hhhhhhhhhhhhhhhhhhhh\n" +
                    "6-12 q: qqqxqqqqgqqpqqqqqqqv\n" +
                    "10-12 g: gqgdgzhgghjgdd\n" +
                    "2-6 p: pnppppp\n" +
                    "3-14 l: lllllllllllllllll\n" +
                    "12-19 h: hhdhhhhvxrfhcshhwxh\n" +
                    "16-18 m: mmrmmmmlmmgmmmmmmmmm\n" +
                    "8-11 t: tntmlpgfttv\n" +
                    "8-11 f: mffffffffff\n" +
                    "15-18 t: tftttttttjwtttjttjt\n" +
                    "5-12 d: pzdrdqxzqzwgzwcgsv\n" +
                    "4-9 d: cdwdmhksdzgd\n" +
                    "9-17 l: mlsllmgdlhlgmfglr\n" +
                    "1-5 r: rrcnr\n" +
                    "3-4 c: ccccccc\n" +
                    "1-2 g: cskvbgnlgnpfrh\n" +
                    "5-10 n: tfnnvnnqbbn\n" +
                    "1-15 g: fxpdggmtrqggdglh\n" +
                    "3-4 t: ftttppdtdbxzqw\n" +
                    "5-6 p: qpxsjt\n" +
                    "8-14 r: bkltjzprkhrhmrg\n" +
                    "1-11 f: gffkkmpflxlqfsf\n" +
                    "1-4 d: vddknn\n" +
                    "5-7 l: llllllvlllll\n" +
                    "2-11 b: bbbbbbbbbbbbb\n" +
                    "1-3 h: hhhh\n" +
                    "13-14 q: jqqqcckhdqkqqj\n" +
                    "4-14 p: mfwcbqxpdkhtdfj\n" +
                    "3-4 g: ggggg\n" +
                    "6-14 v: vvvvvvvvvvvvvvv\n" +
                    "16-18 v: vvvvvvvsvvvsvvvvvv\n" +
                    "9-13 l: llllllllllllllllllll\n" +
                    "3-4 r: zjrr\n" +
                    "6-8 x: xxxxxxxxx\n" +
                    "2-6 p: zlgpps\n" +
                    "3-8 t: ttjtbttjt\n" +
                    "18-19 k: kkkkkkkkkkkklkkkkkk\n" +
                    "8-13 q: hcvnkpnqfzqmqscwf\n" +
                    "15-16 p: ppppppppppppdpmr\n" +
                    "7-12 c: cqccccdcccwsccc\n" +
                    "8-12 d: ddhddddgdddgdddd\n" +
                    "3-4 x: xxxx\n" +
                    "6-8 w: wwwrlzcbwhwlqwwwv\n" +
                    "1-5 h: hhhhdwhhlhph\n" +
                    "4-5 f: fffvz\n" +
                    "3-8 c: ccqqcccc\n" +
                    "3-5 k: xkwkdkh\n" +
                    "2-3 s: ssssshhsss\n" +
                    "4-6 x: gxxxcx\n" +
                    "8-12 l: vsnlqbjltbtlphjtf\n" +
                    "3-6 n: tgpnqxnntkmntvl\n" +
                    "9-12 f: cjzkldhmvclk\n" +
                    "4-7 b: zgpdznb\n" +
                    "1-12 s: ssssnrssssscnssssq\n" +
                    "14-16 p: pppppppppppppwpjp\n" +
                    "4-14 b: xpbbvcbbbspgbbqbw\n" +
                    "5-6 s: smssrb\n" +
                    "5-16 b: tzbdqxgkbxbvzwvt\n" +
                    "2-14 f: vzplvvftrcdmgs\n" +
                    "13-15 t: tttttkthhtzttdt\n" +
                    "2-3 s: vpwss\n" +
                    "9-14 s: sssssssfssssss\n" +
                    "7-13 s: tsnwzxwzjzsjkchlg\n" +
                    "12-15 q: qlqbbfqqvqmcqhvq\n" +
                    "12-13 g: gggggggggggggggggg\n" +
                    "1-3 g: jjdqzgwgggggg\n" +
                    "5-6 n: nlnxnnnwv\n" +
                    "15-16 m: mmmmmmmmmmmmmmmjmmm\n" +
                    "2-6 m: vmrqrmz\n" +
                    "4-5 n: nvnnwb\n" +
                    "13-15 x: xgblxvxmpskqwvlx\n" +
                    "6-7 v: vvvvvvvv\n" +
                    "8-10 r: fsrrdprbrfxhrdv\n" +
                    "4-5 j: jsjjf\n" +
                    "4-6 k: kkkjkkk\n" +
                    "5-9 j: cflfvjjtjljjhbhnj\n" +
                    "9-11 t: xswktxtqrbm\n" +
                    "4-16 r: drrrrrrrrrrrrfwnr\n" +
                    "13-18 p: bbkplmplqmppppspmp\n" +
                    "9-15 r: kgnwvxmcrmltpcgwvrb\n" +
                    "4-5 c: jcwcccnc\n" +
                    "2-4 f: ffff\n" +
                    "8-12 d: rvsdddvdtdcd\n" +
                    "3-10 v: qvdzjhcvsz\n" +
                    "10-11 x: qcmvlvgxkxx\n" +
                    "6-9 s: sxsspsksjssfsnssrvs\n" +
                    "3-7 x: zbxxxxxwrpxgr\n" +
                    "9-17 j: hrppktjsqhzqwxhdz\n" +
                    "5-7 z: nzzzvzswz\n" +
                    "6-7 p: ppppsbpp\n" +
                    "10-13 f: fffffffffhffmfcxffpf\n" +
                    "9-12 f: ffffffffsffmf\n" +
                    "14-15 r: rrrrrrmrrrrmrrzr\n" +
                    "3-6 w: whwwwwwwwwwwm\n" +
                    "7-8 b: btqbbbbbbbz\n" +
                    "13-16 z: zznbbdmbzhjzzzzzmngd\n" +
                    "6-7 q: fqmqltdqqqdwqss\n" +
                    "3-4 h: hphhhhh\n" +
                    "1-3 r: rdgktrmrmdztrkmn\n" +
                    "17-18 w: wwslwwsmwswwfxwwwww\n" +
                    "6-8 p: ppprpppp\n" +
                    "8-10 z: zzzzzdzrztzzzz\n" +
                    "8-11 m: tmldmmwxmjmrmtrmm\n" +
                    "12-16 s: phpprsdvkmsssmssnqwm\n" +
                    "3-4 h: qplnhkhh\n" +
                    "14-19 w: wvxvqzqzdnjjwwtdbwc\n" +
                    "2-4 p: fpnp\n" +
                    "3-5 c: ccccpcccccccc\n" +
                    "3-12 g: ggwggbgfggrxggg\n" +
                    "4-8 r: rrszrgdbrw\n" +
                    "2-4 n: vnmgjtps\n" +
                    "8-10 j: mjjjxjjgjc\n" +
                    "2-6 m: vmmhmm\n" +
                    "3-4 w: vwww\n" +
                    "10-18 v: mvnbqbvcpkvnhqvvbvzv\n" +
                    "15-19 g: ggtggggggbggggxggglg\n" +
                    "7-13 m: mmmmmmjmmmmmmm\n" +
                    "5-11 d: ddxhdndtfdddndxzdqk\n" +
                    "3-11 f: ffnfbfffffgrff\n" +
                    "7-14 w: fflfpgklzlxfwwt\n" +
                    "15-17 d: zxllzgbjrrddnmdhdwp\n" +
                    "1-5 n: nnnnknnn\n" +
                    "15-16 j: ffkjjljgndljjnjscs\n" +
                    "2-3 v: nvvxvntqcrqq\n" +
                    "5-6 c: rcccgpcc\n" +
                    "2-3 j: qjjfrhwljgczj\n" +
                    "5-8 k: kkkkkkkkkk\n" +
                    "1-2 r: rrrrxrcrrr\n" +
                    "1-15 t: ltttttttttttttttt\n" +
                    "4-13 q: prlqzqvgpqslqqcqqjq\n" +
                    "3-12 q: gfbpbdrwrbqt\n" +
                    "2-5 q: qsxccx\n" +
                    "4-9 t: slglllcdkjzdmxt\n" +
                    "2-3 r: rlvrrr\n" +
                    "2-13 w: wwmkwwwjcwbcwzwwcg\n" +
                    "3-4 t: ndkvx\n" +
                    "6-13 b: qflzbbbcfzkbmtx\n" +
                    "6-10 j: pdckwfhkjxqljnjjw\n" +
                    "1-5 j: jjjjjqmj\n" +
                    "2-10 x: xlxxxxxxxfxx\n" +
                    "1-5 r: rvcnr\n" +
                    "4-10 c: cnchrcsgcvncpq\n" +
                    "3-5 j: fjxbj\n" +
                    "4-11 c: ccdlcsxckcx\n" +
                    "12-16 m: mmmmlmvmpcmnmmdbmms\n" +
                    "3-4 q: qqwlqqqq\n" +
                    "2-6 f: kvcfdv\n" +
                    "8-10 m: mmmmmmmmmm\n" +
                    "7-8 j: jjjjjjjj\n" +
                    "5-7 c: ccccncsjc\n" +
                    "7-9 f: fffffrpfplhzfff\n" +
                    "1-6 c: sbcccscccccccccccc\n" +
                    "5-7 j: njpjqxjrljnqjwjgchtj\n" +
                    "11-18 b: gktmxhjwbmbpjrbqkb\n" +
                    "1-4 f: lffbfffffw\n" +
                    "5-6 c: ccccsc\n" +
                    "10-14 v: mkbxvxvgvvvvbv\n" +
                    "5-6 x: jxxxxxx\n" +
                    "4-6 c: qccmhcccw\n" +
                    "3-7 s: qwmtwprsxd\n" +
                    "10-19 d: rkdwbrndmxdsknddddl\n" +
                    "2-5 p: pppppppppppp\n" +
                    "6-7 w: wwffxwc\n" +
                    "2-7 z: pkzcnxr\n" +
                    "5-10 b: bbqbkbtdbbbbb\n" +
                    "10-13 j: qmqgvhzkjmfjhjjm\n" +
                    "5-6 n: nnnnrn\n" +
                    "7-14 n: qgmlsvnjnrdzcdbstxv\n" +
                    "9-16 q: qpllvqpmqlqvkhwqqrsm\n" +
                    "2-4 s: sqpnqsgsssq\n" +
                    "13-15 z: zzzzmzzzzzzzzzzzzg\n" +
                    "10-15 b: bbbdbmqbkjbbtbd\n" +
                    "2-5 h: qrhhhhp\n" +
                    "11-12 x: xxcxhmxxxxxx\n" +
                    "13-18 c: ccccccccccccdccccccc\n" +
                    "12-13 h: knktllrdtgjhhhxpd\n" +
                    "9-13 g: tdpfvzcqgbslgnbxkgpq\n" +
                    "8-15 g: gggggggsggggggxggggg\n" +
                    "1-3 v: wvfvvdvvvvv\n" +
                    "10-11 b: bbbbbbbbbhzb\n" +
                    "15-17 b: bbbbbbbbbbbbbbpttv\n" +
                    "1-7 m: bmmmmmdm\n" +
                    "2-3 h: rhksbfgh\n" +
                    "6-7 w: wwwwwgf\n" +
                    "3-12 h: hkhzhhhhhhhlhhmh\n" +
                    "3-5 x: xxcxpx\n" +
                    "7-9 m: mmdmtmjdxmm\n" +
                    "1-4 n: lnnlnnnnn\n" +
                    "4-9 k: kkkmkkkkbk\n" +
                    "3-4 t: tttt\n" +
                    "5-12 k: tkgwkrwwzcwkhkmk\n" +
                    "4-5 f: fhfvfgwfff\n" +
                    "3-5 h: fmbgjrxgh\n" +
                    "5-6 j: xtwnjj\n" +
                    "11-15 r: rrrrrrrrprqrrrfrr\n" +
                    "13-14 f: fdffffflfffvfff\n" +
                    "1-6 b: krsbnd\n" +
                    "6-7 b: bbbbvxqbl\n" +
                    "1-2 v: vvcvvvv\n" +
                    "7-9 t: ctfcmttht\n" +
                    "2-7 v: bcxhtdwbfqvv\n" +
                    "14-15 n: nnsnlnvkqztnxnn\n" +
                    "2-6 g: rknndvrhbg\n" +
                    "2-6 z: mzzzdzzzz\n" +
                    "11-14 q: qqqqqqvrqqzlqkqqq\n" +
                    "3-4 t: ttcrttjtknjpvwhzm\n" +
                    "8-10 j: jjjjjjjjjjjj\n" +
                    "2-7 c: ccnhcccc\n" +
                    "3-14 m: mmmmmmmmmmmmzmm\n" +
                    "10-16 w: swsmwwwwwrnwmwwk\n" +
                    "4-5 m: bmdjm\n" +
                    "6-11 l: cmlllxllllkrllf\n" +
                    "14-18 t: tttttttttttttvtltt\n" +
                    "11-13 f: ffffffffffhfzfff\n" +
                    "3-6 g: wkzxtrkgr\n" +
                    "7-10 c: cccpcccccvccc\n" +
                    "3-13 m: mmbmmzbcmlwmmfnmmq\n" +
                    "2-3 p: pdszp\n" +
                    "13-14 r: rqrrfrdrrrwvrrrrrwrr\n" +
                    "9-11 g: gggwggggfcpg\n" +
                    "3-9 p: pnppppdpppp\n" +
                    "17-19 k: gzkktkxkkskkkmkkkpk\n" +
                    "4-11 x: bmqhtxzqmvx\n" +
                    "11-14 v: cvsvssqghzjqxm\n" +
                    "1-14 z: zwxczzszzdmkztl\n" +
                    "8-9 t: jkpptwctt\n" +
                    "3-8 z: vqmzzpjj\n" +
                    "6-10 s: msdrxssssswssjz\n" +
                    "1-7 z: zhpzzzz\n" +
                    "13-17 m: mmmmmmmmmlmmgmmmgm\n" +
                    "9-10 n: qgtcnnnnnkcnnn\n" +
                    "2-4 v: vrcvv\n" +
                    "4-5 h: hhhdwh\n" +
                    "8-9 c: zcccccccc\n" +
                    "13-14 p: pjxcpmdpppmgwt\n" +
                    "2-6 c: gskmcc\n" +
                    "6-7 q: qqqqqqqq\n" +
                    "3-13 b: gfbxqtnxnqxbb\n" +
                    "8-10 l: lhrlqlrqlsllll\n" +
                    "5-8 z: jlzgzzzq\n" +
                    "10-13 z: zzzzzzzpzkzzgz\n" +
                    "6-7 d: wddnddd\n" +
                    "10-11 h: vbhhbhhhhbz\n" +
                    "7-10 s: sxssksskqs\n" +
                    "1-12 b: vdgxvsxpgbbpd\n" +
                    "5-6 n: npnvckn\n" +
                    "3-4 v: vvjvv\n" +
                    "9-15 r: njhhqlmcmncjrpx\n" +
                    "2-8 h: bghrdhhrjbhhhbjz\n" +
                    "5-7 q: qqqqlflrq\n" +
                    "9-12 f: qfhfffffffffffff\n" +
                    "2-3 m: mmmblxmbpz\n" +
                    "13-16 v: vvvvvvvqvvvvlvvw\n" +
                    "6-12 b: wbfgbghzbmvf\n" +
                    "12-15 r: rbrrrrthrrrrrrrr\n" +
                    "4-8 k: pkprqkkkpsphwnhp\n" +
                    "8-9 h: hhhhhhhsl\n" +
                    "1-3 b: bsbn\n" +
                    "15-16 j: ktjjjxjfjjrjjcjk\n" +
                    "4-8 z: smzzmzzszzr\n" +
                    "3-4 m: qmmmzqzlrpt\n" +
                    "11-12 n: nnnnngnnnnwgnnnn\n" +
                    "5-10 x: slpbxqfxxxx\n" +
                    "12-19 q: qqqqgqqqsqqqqqqqsqqq\n" +
                    "4-10 s: ssstssssss\n" +
                    "6-11 g: gggggvggggzggggggg\n" +
                    "12-14 c: cckccccdccxnngccc\n" +
                    "3-5 j: jnrjvj\n" +
                    "2-6 t: vtdtms\n" +
                    "13-15 p: ppppppppppppjpq\n" +
                    "1-9 j: jjjjjjjjjjj\n" +
                    "8-9 d: wfdddddkddxd\n" +
                    "3-7 p: pwpcpvp\n" +
                    "3-4 h: hhzl\n" +
                    "9-10 n: lnkjxnsbnn\n" +
                    "7-11 z: zzzzfznzbzbzbzd\n" +
                    "1-2 m: mmzlmkm\n" +
                    "6-7 t: jbmpztx\n" +
                    "5-6 v: vvbvvtn\n" +
                    "7-17 q: lvdfpbqxbxdnwqzjlfs\n" +
                    "3-5 z: zdzzzxczbzzz\n" +
                    "10-14 f: fpffffffffffff\n" +
                    "3-8 x: wxxchxjx\n" +
                    "1-6 x: xxxxxx\n" +
                    "14-15 x: zmxtcbjxtvxxxxg\n" +
                    "4-5 f: qfffghf\n" +
                    "2-3 p: pppp\n" +
                    "10-12 n: nnngnxnnnhnsbntln\n" +
                    "1-2 w: ftwwww\n" +
                    "10-11 f: fffffffffpkf\n" +
                    "4-5 n: nnnnnn\n" +
                    "10-11 r: rrrrtrrlrrrr\n" +
                    "5-6 h: hjhxhhnbhlbxvhs\n" +
                    "1-4 q: qqqq\n" +
                    "7-11 p: dkpfppwzpxqqx\n" +
                    "11-17 l: lzknllnllkgvllllh\n" +
                    "1-3 z: zzzzz\n" +
                    "16-17 b: bbbbbbbbbbbbbbbbbb\n" +
                    "2-4 n: qcpwnhn\n" +
                    "1-4 v: svvhvvv\n" +
                    "10-12 l: llllllllllljl\n" +
                    "1-2 l: xzlllllll\n" +
                    "1-3 l: plklll\n" +
                    "4-8 x: xxxxfxbxcxxqxfxpx\n" +
                    "3-8 b: xgbbwncxclbv\n" +
                    "5-6 m: mmmmmmm\n" +
                    "4-5 p: pptppfnpl\n" +
                    "14-16 x: gwjfkzwrldzxpdxgk\n" +
                    "10-11 z: zzzzvzzzzzzz\n" +
                    "3-12 k: kkxkblkkkkkgkkkmkk\n" +
                    "4-6 p: pppfpx\n" +
                    "2-7 r: rrmrrrrrrrrrr\n" +
                    "7-9 p: pbpfpppppp\n" +
                    "2-3 v: tvvbbjnvv\n" +
                    "5-8 j: jjjjjjjjj\n" +
                    "2-5 c: xcwcczjkvgccccvpkd\n" +
                    "5-7 f: ffffpfqfffff\n" +
                    "11-13 m: qmmmmmmmlwkmmmmmm\n" +
                    "14-15 d: dddddddpmddddszdd\n" +
                    "6-15 b: kptphpbxxqsbxlhxplml\n" +
                    "16-18 x: xxkzfxgqxdcvzdxlzn\n" +
                    "10-12 m: clrmmmmksmmm\n" +
                    "1-3 w: wwpww\n" +
                    "8-15 g: ggggggnlgggggggggng\n" +
                    "3-6 h: tnhhxh\n" +
                    "4-5 l: lllrdllxlnllqll\n" +
                    "1-2 m: lmjhvl\n" +
                    "1-4 k: dkkhkkk\n" +
                    "6-7 x: wncxcxf\n" +
                    "4-5 w: wwwhfww\n" +
                    "4-8 b: bshnbbdbmfxbbrc\n" +
                    "4-7 t: tbdtztm\n" +
                    "7-8 n: zntlhccn\n" +
                    "10-14 f: frgffffffflfzlf\n" +
                    "3-4 b: nzbbbnfbdg\n" +
                    "2-6 m: srmwsmtp\n" +
                    "5-6 z: zzpvsrz\n" +
                    "2-13 m: msmmmhmmmmmmtm\n" +
                    "3-4 c: ccvcc\n" +
                    "1-4 n: nnnnnn\n" +
                    "2-3 j: zdvsj\n" +
                    "4-6 c: ccctccc\n" +
                    "4-5 z: zzpdztnrzl\n" +
                    "4-6 z: hzdzpz\n" +
                    "2-6 x: gxjxcxxjqcb\n" +
                    "4-9 j: jjjvjcgzl\n" +
                    "5-8 z: dmppvjqfzzzzn\n" +
                    "5-7 v: vvvvvvr\n" +
                    "2-5 l: lvkkft\n" +
                    "2-11 n: nnhnqnnvnsn\n" +
                    "1-3 d: dhndddjfd\n" +
                    "8-9 x: xxxxxxxxxxxxxxxxxxxx\n" +
                    "4-9 p: fntpgcwtwv\n" +
                    "4-12 q: qbrlqzqcnwtjq\n" +
                    "2-3 f: ftcjvnfkzx\n" +
                    "1-2 d: dddd\n" +
                    "7-10 g: gggggghggzgg\n" +
                    "4-6 g: zhgbgphggtm\n" +
                    "2-4 l: lblq\n" +
                    "14-17 n: bnnngnnnnnnznnnnn\n" +
                    "5-6 f: fxxffffhmswq\n" +
                    "6-10 p: pppppppppp\n" +
                    "2-4 q: lsxgqkqsblqqq\n" +
                    "11-19 x: xxnrgxxxxxxxxxfwmxx\n" +
                    "4-7 j: jjjtjjljjjjjjj\n" +
                    "6-7 l: llllllll\n" +
                    "1-4 f: pfftffffnffff\n" +
                    "11-13 r: xrrlrrrrrqrrzrr\n" +
                    "1-3 p: pvpqp\n" +
                    "9-13 d: ddddxrnddddfdscsd\n" +
                    "1-2 f: lbbr\n" +
                    "3-7 t: mpttsgwb\n" +
                    "2-10 c: jccchctshcpchwx\n" +
                    "2-4 p: lmpd\n" +
                    "1-2 n: zlnxnnf\n" +
                    "2-3 w: fwwtqw\n" +
                    "9-16 s: sssssssssssssssssssj\n" +
                    "1-5 s: hssrm\n" +
                    "15-17 b: ghpvwjbzpksvhsjbj\n" +
                    "8-9 h: hzrvxhhdz\n" +
                    "3-4 j: mkjjpvkfhprr\n" +
                    "1-8 n: cnnnnnnmnn\n" +
                    "1-4 x: lxxxx\n" +
                    "3-5 m: pjttcvvcmfvzffcfmmv\n" +
                    "3-10 r: rsxtvwjrfrqrrbzzr\n" +
                    "2-7 h: hhckhhr\n" +
                    "7-8 r: srrrmprrrhkzsndrrkr\n" +
                    "4-13 m: pdsmlsnxcmhmmsvc\n" +
                    "3-12 d: ddsdddddddddddddd\n" +
                    "14-16 s: sssssssssssssjsds\n" +
                    "3-4 m: djfp\n" +
                    "2-5 w: bgwpc\n" +
                    "4-5 r: zffrrqrs\n" +
                    "4-9 r: rrrgrrrrqrrrrrrr\n" +
                    "4-6 w: wxwwvw\n" +
                    "7-8 d: tvddddwtdddldd\n" +
                    "6-7 g: tgdggggfzrgqggggmggg\n" +
                    "2-6 t: tgtfdtttttttttqxd\n" +
                    "14-18 f: fffsffgfffffskfkff\n" +
                    "1-12 b: qbvbbbbmbsqbcbgbbbcp\n" +
                    "5-7 d: ddbqhdddsdm\n" +
                    "6-9 n: tqwnckjsn\n" +
                    "1-3 n: nnnn\n" +
                    "5-10 w: wwwwwwwlwwqwwwp\n" +
                    "3-4 r: rrrr\n" +
                    "2-12 m: mmchtqmhfdpm\n" +
                    "6-9 d: dzgzdbddwgdwldb\n" +
                    "10-14 k: kkkkkkkkkkkkkzkkkkk\n" +
                    "13-14 v: vvvvvvvvvvvvvvvv\n" +
                    "2-12 f: btqtbrvkmfzhz\n" +
                    "1-5 b: bbbbbb\n" +
                    "7-10 j: jhjnjjwnjbj\n" +
                    "2-16 h: kjszvtwrjgrvzrqlzcb\n" +
                    "6-8 t: nxzftvtnrtxg\n" +
                    "3-6 h: cvhhnhnhhcgst\n" +
                    "5-8 f: fxgfjnjzz\n" +
                    "11-12 b: bbbbbnbbbzbqbbbq\n" +
                    "1-6 h: hjzhhw\n" +
                    "18-19 m: xrvmftmpkpmrlkqmxvm\n" +
                    "6-7 v: cvxbdsr\n" +
                    "5-6 v: vjvvvvf\n" +
                    "2-3 m: mmzpm\n" +
                    "3-4 k: mkghkxc\n" +
                    "1-6 s: sjsmjsstsss\n" +
                    "2-10 s: wndvkxbmffh\n" +
                    "9-15 q: qqqqqqqqqqqqqqqqq\n" +
                    "4-5 f: rffffpc\n" +
                    "10-11 v: vvvvvvrvvlmv\n" +
                    "6-7 n: tnnnnlq\n" +
                    "16-18 g: gggggdgdgggggggggggg\n" +
                    "5-11 l: lwlfvzlsjll\n" +
                    "11-14 v: vvvvvvvrvwvvvv\n" +
                    "12-16 j: jjjjjjjjjjjpjjjx\n" +
                    "4-6 w: wwwwwr\n" +
                    "2-4 d: ncdd\n" +
                    "15-17 c: nccccctccwccccqcqcc\n" +
                    "3-5 m: mnlmqtsvn\n" +
                    "7-8 w: swwwwwnl\n" +
                    "6-12 l: zlplklqldllxlpvb\n" +
                    "7-9 h: fhkhqnfhhzrhqhhh\n" +
                    "11-14 v: vvvvvvvvvvvvvv\n" +
                    "16-18 v: vnvvsllmvswcvzqvvxjl\n" +
                    "7-9 k: kkkzkkkkskkkzkkkjlk\n" +
                    "5-17 w: wckwxwlrlwrncxwwb\n" +
                    "2-4 v: vqvvqgx\n" +
                    "2-3 b: bbbbbbmbbbbqb\n" +
                    "4-5 p: ptphbprpv\n" +
                    "3-6 q: kqqkpqbnt\n" +
                    "15-20 n: nnnnnnngnnnnnnnnnnnw\n" +
                    "10-12 p: pppppxpppmpnjp\n" +
                    "5-10 x: bhwlxkrdxxqvkphvmfgn\n" +
                    "2-3 l: lllhql\n" +
                    "4-11 l: wllvwfccllk\n" +
                    "7-11 d: dmvmmzlngpw\n" +
                    "2-6 v: rskbvv\n" +
                    "7-9 k: kwtckkkkx\n" +
                    "11-12 j: jnjjfzjjjjjjjj\n" +
                    "2-5 v: rvvnnjjxjnnt\n" +
                    "2-6 j: ljcqpjmhgmmcxjkgd\n" +
                    "1-3 k: lklbx\n" +
                    "14-15 c: ccccccccccccckc\n" +
                    "2-6 x: xxxxxxxxxxxx\n" +
                    "1-7 t: btrtxtjgtt\n" +
                    "2-3 t: sttt\n" +
                    "5-7 k: kkkkzksxgb\n" +
                    "3-4 q: mnnxqwtnw\n" +
                    "8-10 t: vwzmnxjdzx\n" +
                    "4-10 f: svglffffpzw\n" +
                    "1-5 s: dsfjsv\n" +
                    "8-10 m: vmwpmmmjmv\n" +
                    "6-7 h: hhhhhwxhhhhhhhhhhhhh\n" +
                    "7-19 n: ktlblznjctnnrzwrknt\n" +
                    "3-6 n: nzxclnvc\n" +
                    "2-5 t: wtrttkx\n" +
                    "9-10 j: jjjjjjxjjj\n" +
                    "12-13 r: rrrrrjrrrrrwx\n" +
                    "11-16 c: plvcnjcpnkvcpcmcpbc\n" +
                    "2-3 c: gccclcslqdmsg\n" +
                    "10-13 d: dddddddddhddd\n" +
                    "8-9 w: kklwmwqmwwtwqw\n" +
                    "2-5 q: qsqqwx\n" +
                    "3-4 c: hcqvfbccccctcc\n" +
                    "6-7 k: kkkwqgv\n" +
                    "13-15 h: qhhmhkjvhhhhngnhhhhs\n" +
                    "4-5 d: msjdd\n" +
                    "6-7 g: ggggggg\n" +
                    "5-8 r: cqrdrfxnrrjrsr\n" +
                    "9-15 r: lprrqrrrrrrrrrrbr\n" +
                    "6-7 h: hhrqhrlhhh\n" +
                    "2-3 g: glgg\n" +
                    "1-11 n: nnnnnnnnlnnjzwnnnn\n" +
                    "3-6 l: bwllrl\n" +
                    "2-6 p: nptphqv\n" +
                    "3-8 l: lrlknvlpcm\n" +
                    "2-8 g: wjbgpjrlfsgg\n" +
                    "5-6 w: swwfww\n" +
                    "1-8 p: pptpxppppppwpppfx\n" +
                    "3-4 d: wlddg\n" +
                    "15-17 c: sccccccgccccccccc\n" +
                    "4-6 n: nnnhnp\n" +
                    "8-9 r: prvrxmprlzxs\n" +
                    "9-12 t: ttttttttttttkrtt\n" +
                    "5-6 h: hhhhkfh\n" +
                    "1-10 q: psqpzpkqtcq\n" +
                    "4-7 f: ffflnfzkf\n" +
                    "10-11 j: jjjvjjxfjjj\n" +
                    "4-11 p: wlhgrxlclnt\n" +
                    "1-14 t: wfntvttxmldhqg\n" +
                    "14-19 c: ccpczqrccfhtcvljlvc\n" +
                    "11-12 w: wwwwwwwwwwwww\n" +
                    "2-8 z: lzsdqxzz\n" +
                    "17-18 p: pppppppppppqphppprpp\n" +
                    "2-4 j: wjjq\n" +
                    "4-6 f: ffkfffgff\n" +
                    "8-20 x: phxxxxxnwxxdqzxxxxxx\n" +
                    "9-10 d: xvddddsldd\n" +
                    "3-10 l: rglllxlnfl\n" +
                    "6-15 d: ddddddgddpddddwd\n" +
                    "6-7 w: kwwwwhs\n" +
                    "8-10 r: rrrfmrrrrd\n" +
                    "2-11 x: xcjcgtkzkhtmrxqjxxx\n" +
                    "4-5 v: wvmdr\n" +
                    "7-8 d: dddddddd\n" +
                    "7-13 l: lllllldlxllln\n" +
                    "13-14 z: zzdrzzzffzzzzzznzz\n" +
                    "3-4 j: zjjj\n" +
                    "8-9 s: sssssssbss\n" +
                    "6-15 f: pfsfvfxqpffqfqf\n" +
                    "9-11 p: pjpppprzpcphvppwp\n" +
                    "3-4 c: ccrd\n" +
                    "9-10 c: qcwbccccjhwvtwcccnc\n" +
                    "3-4 x: xgxx\n" +
                    "5-6 x: xgxzxxxxxxx\n" +
                    "5-10 l: kxdgnqrkpqgcmcmnk\n" +
                    "4-7 v: vvvpvvvv\n" +
                    "1-4 n: nqnnnnnn\n" +
                    "5-6 p: pprgpst\n" +
                    "14-20 q: wlxrjczhxwdctvpcgxqc\n" +
                    "5-8 g: gcggbggggggzgg\n" +
                    "10-11 g: ggggtggggggg\n" +
                    "14-18 h: hhchhhmhhbwhhlhsvrh\n" +
                    "3-6 f: ffmfffffffff\n" +
                    "1-12 n: rnnnnjwnnnnv\n" +
                    "7-12 l: bpxlhthjplljwxvvvjm\n" +
                    "4-5 j: jhjjjjj\n" +
                    "9-12 q: qvqqqqqvqsqq\n" +
                    "3-4 d: ddnvdddddgddd\n" +
                    "1-7 h: xhhhhhkh\n" +
                    "1-4 f: fffff\n" +
                    "3-4 q: qfrq\n" +
                    "5-8 k: kkkkgkkqkk\n" +
                    "14-18 k: nkkkkkkfkkwkkkkkqk\n" +
                    "1-4 q: qqdc\n" +
                    "17-18 f: ffffffffhffffffffff\n" +
                    "16-17 b: bbbbbbbbbbbbbbbdm\n" +
                    "17-18 z: zzzzzzzzzznzzzvzmwzz\n" +
                    "3-4 g: tggd\n" +
                    "4-6 t: mlttlqqz\n" +
                    "11-18 f: fgffgwlffffftfzfrt\n" +
                    "7-9 h: hmmhhhpljjn\n" +
                    "16-17 m: mmrsnmmzfhtmrjwmmjm\n" +
                    "2-3 l: cllcbm\n" +
                    "3-4 k: fkkkqbpbmmcd\n" +
                    "9-10 f: kfmchwkwzfh\n" +
                    "5-6 j: jjmjjjjjj\n" +
                    "3-5 v: vsvbfvvh\n" +
                    "3-4 k: tgkk\n" +
                    "2-8 k: lscvjjnhpxl\n" +
                    "7-8 v: vvlvvfkqqv\n" +
                    "8-9 q: qcqqtqqhqvqqtq\n" +
                    "12-14 z: zzzhzwzzqzzzzwzzlz\n" +
                    "5-8 k: kzknkkkkkp\n" +
                    "5-6 s: spsssw\n" +
                    "2-3 k: kmkh\n" +
                    "9-10 f: vnlxmstqbsg\n" +
                    "1-2 k: kkkk\n" +
                    "6-15 r: rcrrrsrrrrrrrrzrrqrr\n" +
                    "3-8 c: cfczjwkcxbc\n" +
                    "15-16 k: kkkkgkkkkkkkkkkh\n" +
                    "5-18 c: ccdcxtccccccpcfccv\n" +
                    "6-11 w: qdwnfhzlwwwwxwwgwhwk\n" +
                    "1-6 d: fddddddhddw\n" +
                    "7-10 p: wpbppvpzwc\n" +
                    "12-14 k: kkkkkkkkkkhhkslsk\n" +
                    "4-7 r: hdrrfhrqrdmcbnlrrjbr\n" +
                    "7-10 b: bbbbbjbbbbbb\n" +
                    "4-7 p: pzppzppsp\n" +
                    "11-12 h: qhhhhhhqhrlwlhhthh\n" +
                    "6-9 s: sbssxsskswvp\n" +
                    "17-18 b: bbmpbbhhbnsbbbbbbb\n" +
                    "8-9 g: wgggktggg\n" +
                    "1-12 s: vsssssfssssrqk\n" +
                    "2-5 s: bsgssxc\n" +
                    "3-4 c: ccccccc\n" +
                    "2-3 d: dddd\n" +
                    "5-7 r: ldlcjrrlrngr\n" +
                    "5-10 m: msmjqmmmmm\n" +
                    "3-7 c: ccccccccc\n" +
                    "13-14 p: pppxpppppppppcpppp\n" +
                    "2-3 r: jrfrvrk\n" +
                    "11-12 g: gggggggggggg\n" +
                    "6-18 t: ctvqgcrgnxdvbzjfrrbt\n" +
                    "6-11 f: rnjptfnwgxfp\n" +
                    "5-8 w: wwwtwwwwww\n" +
                    "14-15 r: rkrbrvrrrgrczrz\n" +
                    "12-13 t: trtjtttlnxnxx\n" +
                    "5-8 l: qnwllfsl\n" +
                    "2-15 g: xgtcjftlqqfwkggpf\n" +
                    "11-16 j: jjjjjjjjjljjjjjjj\n" +
                    "8-9 b: bbzbkbbvgcbb\n" +
                    "5-6 r: dvkxrrsvrrksszsdr\n" +
                    "12-13 j: jjjjjjjjjjjhdjjj\n" +
                    "16-17 z: mzzzrxfzzzzczzgzz\n" +
                    "2-15 p: lpjxcdzjmnghfppr\n" +
                    "9-15 s: ssssssssnsssssss\n" +
                    "1-11 t: tfvtqvlbtld\n" +
                    "4-5 k: kkkczkkkvkkk\n" +
                    "2-7 p: ptphppvppppp\n";

    public List<String[]> getInputAsStringList() {
        List<String[]> inputToReturn= new ArrayList<>();

        final String[] inputSplit = this.input.split("\n");

        List<String> temp= new ArrayList<>();
        for (String singleInput : inputSplit) {
            temp.add(singleInput);
        }

        for (String singleInput : inputSplit) {
            String[] parts = singleInput.split(" ");
            inputToReturn.add(parts);
        }

        return inputToReturn;
    }
}
