package com.year21.day2;

import java.util.ArrayList;
import java.util.List;

public class Input {
    private static String exampleInput =
                    "forward 5\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "up 3\n" +
                    "down 8\n" +
                    "forward 2";

    private static String input =
                    "forward 8\n" +
                    "forward 3\n" +
                    "down 8\n" +
                    "down 2\n" +
                    "up 1\n" +
                    "up 4\n" +
                    "down 9\n" +
                    "forward 3\n" +
                    "forward 4\n" +
                    "forward 5\n" +
                    "forward 1\n" +
                    "forward 1\n" +
                    "up 8\n" +
                    "forward 2\n" +
                    "forward 9\n" +
                    "down 2\n" +
                    "forward 8\n" +
                    "down 5\n" +
                    "down 3\n" +
                    "down 8\n" +
                    "up 1\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "up 7\n" +
                    "down 8\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "forward 9\n" +
                    "down 2\n" +
                    "down 5\n" +
                    "forward 1\n" +
                    "down 1\n" +
                    "forward 2\n" +
                    "up 8\n" +
                    "down 8\n" +
                    "forward 2\n" +
                    "up 5\n" +
                    "down 6\n" +
                    "down 5\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "forward 4\n" +
                    "forward 6\n" +
                    "down 4\n" +
                    "up 1\n" +
                    "down 8\n" +
                    "down 7\n" +
                    "down 3\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 7\n" +
                    "down 3\n" +
                    "down 3\n" +
                    "forward 3\n" +
                    "down 2\n" +
                    "up 8\n" +
                    "up 8\n" +
                    "forward 2\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "forward 3\n" +
                    "forward 9\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "down 9\n" +
                    "down 3\n" +
                    "forward 4\n" +
                    "forward 1\n" +
                    "down 7\n" +
                    "forward 5\n" +
                    "up 2\n" +
                    "down 6\n" +
                    "up 4\n" +
                    "down 2\n" +
                    "up 5\n" +
                    "forward 6\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "forward 5\n" +
                    "forward 4\n" +
                    "up 8\n" +
                    "up 5\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "up 1\n" +
                    "forward 9\n" +
                    "up 5\n" +
                    "up 5\n" +
                    "forward 3\n" +
                    "down 6\n" +
                    "forward 7\n" +
                    "down 2\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "down 6\n" +
                    "down 3\n" +
                    "down 1\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "forward 2\n" +
                    "down 1\n" +
                    "down 2\n" +
                    "forward 6\n" +
                    "forward 1\n" +
                    "forward 7\n" +
                    "forward 2\n" +
                    "down 2\n" +
                    "up 6\n" +
                    "up 2\n" +
                    "forward 7\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "forward 5\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "down 3\n" +
                    "up 1\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "down 2\n" +
                    "down 5\n" +
                    "up 8\n" +
                    "down 8\n" +
                    "forward 3\n" +
                    "down 9\n" +
                    "forward 8\n" +
                    "down 8\n" +
                    "down 5\n" +
                    "forward 2\n" +
                    "up 1\n" +
                    "down 3\n" +
                    "up 3\n" +
                    "down 5\n" +
                    "down 7\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "down 1\n" +
                    "forward 9\n" +
                    "up 4\n" +
                    "up 4\n" +
                    "down 5\n" +
                    "forward 6\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "forward 5\n" +
                    "up 6\n" +
                    "forward 1\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "down 8\n" +
                    "forward 6\n" +
                    "forward 6\n" +
                    "up 1\n" +
                    "down 6\n" +
                    "forward 2\n" +
                    "down 7\n" +
                    "down 2\n" +
                    "forward 4\n" +
                    "up 4\n" +
                    "up 2\n" +
                    "forward 8\n" +
                    "up 6\n" +
                    "down 8\n" +
                    "up 3\n" +
                    "down 5\n" +
                    "down 3\n" +
                    "forward 3\n" +
                    "down 8\n" +
                    "up 4\n" +
                    "up 5\n" +
                    "down 1\n" +
                    "down 7\n" +
                    "down 7\n" +
                    "forward 6\n" +
                    "up 6\n" +
                    "down 1\n" +
                    "forward 7\n" +
                    "down 2\n" +
                    "up 7\n" +
                    "up 3\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "up 4\n" +
                    "up 1\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "down 3\n" +
                    "down 1\n" +
                    "forward 8\n" +
                    "up 7\n" +
                    "down 3\n" +
                    "up 5\n" +
                    "down 3\n" +
                    "down 9\n" +
                    "down 9\n" +
                    "up 9\n" +
                    "down 9\n" +
                    "up 4\n" +
                    "down 5\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "forward 1\n" +
                    "up 3\n" +
                    "down 9\n" +
                    "down 8\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "forward 9\n" +
                    "forward 3\n" +
                    "forward 3\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "forward 1\n" +
                    "up 9\n" +
                    "up 3\n" +
                    "forward 1\n" +
                    "forward 2\n" +
                    "forward 7\n" +
                    "forward 8\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "forward 7\n" +
                    "down 1\n" +
                    "up 7\n" +
                    "up 3\n" +
                    "forward 3\n" +
                    "forward 9\n" +
                    "down 7\n" +
                    "down 3\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "up 1\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "up 2\n" +
                    "down 1\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "up 3\n" +
                    "forward 3\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "forward 2\n" +
                    "down 8\n" +
                    "forward 3\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "forward 6\n" +
                    "forward 5\n" +
                    "down 5\n" +
                    "forward 2\n" +
                    "up 7\n" +
                    "up 7\n" +
                    "down 8\n" +
                    "forward 9\n" +
                    "up 1\n" +
                    "up 5\n" +
                    "up 8\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "up 5\n" +
                    "down 3\n" +
                    "forward 6\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "down 7\n" +
                    "down 8\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "forward 1\n" +
                    "forward 3\n" +
                    "forward 5\n" +
                    "down 9\n" +
                    "up 3\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "down 5\n" +
                    "forward 3\n" +
                    "forward 7\n" +
                    "down 3\n" +
                    "forward 8\n" +
                    "down 1\n" +
                    "down 3\n" +
                    "down 4\n" +
                    "down 2\n" +
                    "forward 8\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "down 2\n" +
                    "up 2\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "down 9\n" +
                    "up 1\n" +
                    "down 6\n" +
                    "forward 2\n" +
                    "up 1\n" +
                    "forward 6\n" +
                    "down 2\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "forward 4\n" +
                    "forward 9\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "forward 7\n" +
                    "forward 1\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "down 4\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "down 1\n" +
                    "forward 4\n" +
                    "down 5\n" +
                    "up 3\n" +
                    "down 5\n" +
                    "forward 6\n" +
                    "down 6\n" +
                    "down 4\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 7\n" +
                    "up 4\n" +
                    "forward 6\n" +
                    "down 9\n" +
                    "down 5\n" +
                    "down 5\n" +
                    "up 2\n" +
                    "forward 8\n" +
                    "up 5\n" +
                    "down 1\n" +
                    "down 2\n" +
                    "up 6\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "up 5\n" +
                    "forward 4\n" +
                    "up 5\n" +
                    "down 3\n" +
                    "up 7\n" +
                    "forward 4\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "down 7\n" +
                    "down 3\n" +
                    "down 9\n" +
                    "up 8\n" +
                    "down 9\n" +
                    "forward 6\n" +
                    "forward 2\n" +
                    "forward 2\n" +
                    "up 8\n" +
                    "up 2\n" +
                    "down 4\n" +
                    "down 4\n" +
                    "up 7\n" +
                    "up 9\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "up 8\n" +
                    "forward 8\n" +
                    "up 2\n" +
                    "down 3\n" +
                    "forward 9\n" +
                    "down 1\n" +
                    "down 7\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "up 6\n" +
                    "up 6\n" +
                    "down 9\n" +
                    "forward 6\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "forward 8\n" +
                    "up 1\n" +
                    "down 5\n" +
                    "forward 1\n" +
                    "down 6\n" +
                    "up 8\n" +
                    "forward 2\n" +
                    "up 7\n" +
                    "forward 5\n" +
                    "down 5\n" +
                    "up 3\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "down 6\n" +
                    "up 9\n" +
                    "forward 9\n" +
                    "down 8\n" +
                    "forward 2\n" +
                    "down 1\n" +
                    "down 3\n" +
                    "forward 2\n" +
                    "forward 9\n" +
                    "up 1\n" +
                    "forward 9\n" +
                    "down 4\n" +
                    "forward 2\n" +
                    "forward 7\n" +
                    "forward 1\n" +
                    "up 2\n" +
                    "up 2\n" +
                    "down 9\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "down 6\n" +
                    "up 8\n" +
                    "down 4\n" +
                    "forward 8\n" +
                    "up 9\n" +
                    "up 6\n" +
                    "down 5\n" +
                    "up 1\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "down 1\n" +
                    "up 8\n" +
                    "down 1\n" +
                    "forward 3\n" +
                    "down 7\n" +
                    "down 7\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "forward 1\n" +
                    "forward 4\n" +
                    "forward 5\n" +
                    "down 8\n" +
                    "down 2\n" +
                    "down 9\n" +
                    "up 5\n" +
                    "down 8\n" +
                    "down 8\n" +
                    "down 3\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "up 5\n" +
                    "down 1\n" +
                    "down 2\n" +
                    "forward 9\n" +
                    "down 7\n" +
                    "down 7\n" +
                    "down 1\n" +
                    "down 6\n" +
                    "up 6\n" +
                    "up 7\n" +
                    "down 1\n" +
                    "down 3\n" +
                    "down 2\n" +
                    "down 5\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 5\n" +
                    "forward 1\n" +
                    "up 7\n" +
                    "down 7\n" +
                    "forward 6\n" +
                    "forward 4\n" +
                    "down 3\n" +
                    "forward 3\n" +
                    "forward 6\n" +
                    "forward 7\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "down 6\n" +
                    "down 8\n" +
                    "forward 3\n" +
                    "up 3\n" +
                    "forward 4\n" +
                    "forward 3\n" +
                    "down 6\n" +
                    "up 7\n" +
                    "forward 8\n" +
                    "forward 4\n" +
                    "down 7\n" +
                    "down 6\n" +
                    "down 8\n" +
                    "forward 9\n" +
                    "down 6\n" +
                    "down 5\n" +
                    "up 4\n" +
                    "down 6\n" +
                    "down 8\n" +
                    "down 5\n" +
                    "up 4\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "forward 2\n" +
                    "down 2\n" +
                    "up 7\n" +
                    "down 2\n" +
                    "up 5\n" +
                    "forward 3\n" +
                    "down 8\n" +
                    "forward 3\n" +
                    "forward 8\n" +
                    "up 3\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "forward 2\n" +
                    "up 7\n" +
                    "down 8\n" +
                    "forward 8\n" +
                    "down 2\n" +
                    "down 3\n" +
                    "down 5\n" +
                    "forward 4\n" +
                    "forward 5\n" +
                    "down 2\n" +
                    "forward 2\n" +
                    "down 5\n" +
                    "down 9\n" +
                    "forward 4\n" +
                    "forward 3\n" +
                    "forward 2\n" +
                    "down 9\n" +
                    "forward 2\n" +
                    "forward 9\n" +
                    "down 5\n" +
                    "down 9\n" +
                    "down 6\n" +
                    "down 6\n" +
                    "down 3\n" +
                    "down 1\n" +
                    "down 7\n" +
                    "forward 7\n" +
                    "forward 2\n" +
                    "up 9\n" +
                    "forward 4\n" +
                    "up 7\n" +
                    "forward 3\n" +
                    "down 2\n" +
                    "up 8\n" +
                    "up 3\n" +
                    "down 4\n" +
                    "up 9\n" +
                    "forward 1\n" +
                    "down 1\n" +
                    "forward 4\n" +
                    "up 4\n" +
                    "forward 4\n" +
                    "up 8\n" +
                    "forward 7\n" +
                    "down 3\n" +
                    "forward 1\n" +
                    "up 3\n" +
                    "up 1\n" +
                    "up 2\n" +
                    "down 3\n" +
                    "forward 5\n" +
                    "down 6\n" +
                    "down 1\n" +
                    "down 2\n" +
                    "forward 2\n" +
                    "down 3\n" +
                    "up 1\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "forward 7\n" +
                    "forward 7\n" +
                    "down 5\n" +
                    "down 7\n" +
                    "forward 8\n" +
                    "up 2\n" +
                    "down 6\n" +
                    "forward 1\n" +
                    "down 4\n" +
                    "forward 5\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "forward 7\n" +
                    "down 1\n" +
                    "down 3\n" +
                    "down 1\n" +
                    "down 2\n" +
                    "forward 3\n" +
                    "up 3\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 2\n" +
                    "up 8\n" +
                    "up 6\n" +
                    "up 3\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "down 8\n" +
                    "down 6\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "down 8\n" +
                    "forward 8\n" +
                    "up 7\n" +
                    "up 4\n" +
                    "up 5\n" +
                    "down 4\n" +
                    "up 6\n" +
                    "forward 2\n" +
                    "forward 9\n" +
                    "down 9\n" +
                    "forward 6\n" +
                    "down 5\n" +
                    "down 7\n" +
                    "forward 5\n" +
                    "up 5\n" +
                    "forward 2\n" +
                    "up 7\n" +
                    "up 3\n" +
                    "down 8\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "down 2\n" +
                    "down 5\n" +
                    "forward 4\n" +
                    "down 8\n" +
                    "forward 5\n" +
                    "forward 4\n" +
                    "down 9\n" +
                    "forward 1\n" +
                    "down 4\n" +
                    "up 5\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "forward 4\n" +
                    "down 4\n" +
                    "forward 4\n" +
                    "down 8\n" +
                    "up 5\n" +
                    "up 4\n" +
                    "up 9\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "down 3\n" +
                    "forward 2\n" +
                    "down 6\n" +
                    "down 6\n" +
                    "down 5\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "up 1\n" +
                    "down 9\n" +
                    "down 4\n" +
                    "down 1\n" +
                    "up 4\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "down 4\n" +
                    "up 4\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "up 2\n" +
                    "forward 4\n" +
                    "down 2\n" +
                    "down 3\n" +
                    "down 6\n" +
                    "up 2\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "forward 1\n" +
                    "down 1\n" +
                    "up 7\n" +
                    "up 4\n" +
                    "forward 2\n" +
                    "forward 4\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "down 9\n" +
                    "down 5\n" +
                    "down 1\n" +
                    "down 1\n" +
                    "down 6\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "down 4\n" +
                    "down 9\n" +
                    "down 2\n" +
                    "down 2\n" +
                    "down 5\n" +
                    "up 6\n" +
                    "forward 4\n" +
                    "forward 1\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "forward 2\n" +
                    "down 6\n" +
                    "forward 1\n" +
                    "down 8\n" +
                    "down 1\n" +
                    "forward 2\n" +
                    "forward 3\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "down 5\n" +
                    "up 1\n" +
                    "forward 1\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "forward 8\n" +
                    "down 9\n" +
                    "up 7\n" +
                    "forward 6\n" +
                    "forward 2\n" +
                    "forward 8\n" +
                    "down 9\n" +
                    "down 1\n" +
                    "up 5\n" +
                    "down 5\n" +
                    "down 3\n" +
                    "forward 6\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "forward 6\n" +
                    "up 4\n" +
                    "forward 1\n" +
                    "down 9\n" +
                    "forward 5\n" +
                    "up 1\n" +
                    "down 5\n" +
                    "down 6\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "up 9\n" +
                    "down 6\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "down 3\n" +
                    "forward 7\n" +
                    "down 5\n" +
                    "up 6\n" +
                    "forward 3\n" +
                    "up 4\n" +
                    "down 5\n" +
                    "up 5\n" +
                    "up 9\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "down 9\n" +
                    "forward 9\n" +
                    "down 2\n" +
                    "forward 5\n" +
                    "forward 5\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "up 8\n" +
                    "down 7\n" +
                    "up 9\n" +
                    "forward 8\n" +
                    "forward 8\n" +
                    "down 1\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "up 8\n" +
                    "forward 4\n" +
                    "forward 7\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "down 6\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "forward 5\n" +
                    "forward 7\n" +
                    "forward 5\n" +
                    "forward 2\n" +
                    "forward 7\n" +
                    "up 2\n" +
                    "down 8\n" +
                    "down 9\n" +
                    "down 5\n" +
                    "down 9\n" +
                    "forward 5\n" +
                    "forward 8\n" +
                    "forward 9\n" +
                    "up 5\n" +
                    "down 9\n" +
                    "down 7\n" +
                    "forward 4\n" +
                    "down 6\n" +
                    "up 5\n" +
                    "up 8\n" +
                    "down 3\n" +
                    "down 2\n" +
                    "up 7\n" +
                    "forward 9\n" +
                    "down 3\n" +
                    "down 2\n" +
                    "down 7\n" +
                    "down 4\n" +
                    "up 6\n" +
                    "up 4\n" +
                    "down 7\n" +
                    "down 4\n" +
                    "forward 5\n" +
                    "forward 6\n" +
                    "up 6\n" +
                    "down 7\n" +
                    "down 9\n" +
                    "down 9\n" +
                    "down 6\n" +
                    "forward 8\n" +
                    "forward 3\n" +
                    "forward 5\n" +
                    "up 1\n" +
                    "up 8\n" +
                    "forward 4\n" +
                    "forward 6\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "forward 5\n" +
                    "forward 9\n" +
                    "down 4\n" +
                    "up 3\n" +
                    "up 8\n" +
                    "down 7\n" +
                    "up 8\n" +
                    "forward 5\n" +
                    "forward 3\n" +
                    "up 4\n" +
                    "up 9\n" +
                    "forward 6\n" +
                    "down 1\n" +
                    "up 6\n" +
                    "down 5\n" +
                    "down 4\n" +
                    "down 3\n" +
                    "down 8\n" +
                    "up 1\n" +
                    "down 1\n" +
                    "up 8\n" +
                    "up 8\n" +
                    "down 6\n" +
                    "forward 4\n" +
                    "forward 9\n" +
                    "down 4\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 8\n" +
                    "up 6\n" +
                    "down 9\n" +
                    "up 3\n" +
                    "down 8\n" +
                    "forward 4\n" +
                    "forward 6\n" +
                    "forward 9\n" +
                    "up 7\n" +
                    "down 2\n" +
                    "forward 2\n" +
                    "forward 1\n" +
                    "forward 5\n" +
                    "up 9\n" +
                    "up 7\n" +
                    "up 5\n" +
                    "forward 4\n" +
                    "forward 5\n" +
                    "forward 4\n" +
                    "up 5\n" +
                    "forward 4\n" +
                    "up 6\n" +
                    "down 5\n" +
                    "up 2\n" +
                    "forward 5\n" +
                    "forward 5\n" +
                    "down 9\n" +
                    "forward 7\n" +
                    "down 9\n" +
                    "up 4\n" +
                    "up 9\n" +
                    "forward 6\n" +
                    "forward 7\n" +
                    "down 2\n" +
                    "forward 4\n" +
                    "down 9\n" +
                    "down 6\n" +
                    "forward 1\n" +
                    "forward 7\n" +
                    "up 3\n" +
                    "up 3\n" +
                    "down 6\n" +
                    "up 6\n" +
                    "up 2\n" +
                    "up 3\n" +
                    "forward 7\n" +
                    "up 4\n" +
                    "forward 1\n" +
                    "down 1\n" +
                    "forward 2\n" +
                    "forward 4\n" +
                    "down 1\n" +
                    "down 8\n" +
                    "forward 5\n" +
                    "forward 8\n" +
                    "up 7\n" +
                    "down 3\n" +
                    "forward 3\n" +
                    "forward 6\n" +
                    "down 8\n" +
                    "down 7\n" +
                    "up 9\n" +
                    "forward 3\n" +
                    "up 1\n" +
                    "down 8\n" +
                    "forward 4\n" +
                    "down 9\n" +
                    "forward 3\n" +
                    "forward 8\n" +
                    "down 4\n" +
                    "forward 4\n" +
                    "forward 1\n" +
                    "up 6\n" +
                    "down 1\n" +
                    "down 7\n" +
                    "forward 8\n" +
                    "down 9\n" +
                    "down 8\n" +
                    "down 7\n" +
                    "forward 5\n" +
                    "up 6\n" +
                    "forward 5\n" +
                    "up 1\n" +
                    "down 3\n" +
                    "down 7\n" +
                    "down 4\n" +
                    "forward 6\n" +
                    "down 4\n" +
                    "down 7\n" +
                    "up 9\n" +
                    "down 6\n" +
                    "down 7\n" +
                    "up 3\n" +
                    "up 8\n" +
                    "forward 3\n" +
                    "forward 1\n" +
                    "forward 5\n" +
                    "down 5\n" +
                    "forward 5\n" +
                    "down 1\n" +
                    "forward 9\n" +
                    "up 5\n" +
                    "forward 4\n" +
                    "down 1\n" +
                    "down 8\n" +
                    "up 1\n" +
                    "up 3\n" +
                    "up 8\n" +
                    "down 3\n" +
                    "down 5\n" +
                    "up 7\n" +
                    "forward 4\n" +
                    "down 7\n" +
                    "forward 9\n" +
                    "forward 7\n" +
                    "forward 9\n" +
                    "down 9\n" +
                    "forward 3\n" +
                    "forward 6\n" +
                    "up 3\n" +
                    "forward 4\n" +
                    "forward 4\n";

    public static List<String[]> getPlannedCourseAsStringArrayList() {
        String[] s = input.split("\n");
//        String[] s = exampleInput.split("\n");
        List<String[]> plannedCourse = new ArrayList<>();

        for (String movement : s) {
            String[] splitMovement = movement.split(" ");
            plannedCourse.add(splitMovement);
        }

        return plannedCourse;
    }
}
